configfile: 'config/config_PBMC.yaml'

SAMPLES = [str(i) for i in range(1, 33)] # range(1, 33)

rule find_enhancer_pairs:
    input:
        expand('results/SCENT_outputs/SCENT_output_{sample}.csv', sample=SAMPLES)
    output:
        'results/SCENT_peak_gene/significant_peak_gene_associations.csv',
        expand('results/enhancer_pairs/enhancer_pairs_{sample}.csv', sample=SAMPLES),
        'results/SCENT_peak_gene/SCENT_gene_set.csv'
    conda:
        'envs/pandas.yaml'
    script:
        'scripts/find_enhancer_pairs.py'

rule run_epistasis_model_11_00:
    input:
        config['rna'],
        config['atac'],
        config['meta'],
        'results/enhancer_pairs/enhancer_pairs_{sample}.csv'
    output:
        'results/epistasis_models/epistasis_models_11_00_{sample}.csv'
    params:
        celltype = config['celltype']
    conda:
        'envs/seurat.yaml'
    script:
        'scripts/run_epistasis_model_11_00.R'

rule run_epistasis_model_11_00_input:
    input:
        expand('results/epistasis_models/epistasis_models_11_00_{sample}.csv', sample=SAMPLES)

rule run_epistasis_model_01_10:
    input:
        config['rna'],
        config['atac'],
        config['meta'],
        'results/enhancer_pairs/enhancer_pairs_{sample}.csv'
    output:
        'results/epistasis_models/epistasis_models_01_10_{sample}.csv'
    params:
        celltype = config['celltype']
    conda:
        'envs/seurat.yaml'
    script:
        'scripts/run_epistasis_model_01_10.R'

rule run_epistasis_model_01_10_input:
    input:
        expand('results/epistasis_models/epistasis_models_01_10_{sample}.csv', sample=SAMPLES)
