configfile: 'config/config_PBMC.yaml'

SAMPLES = range(1, 33)

rule run_SCENT:
    input:
        config['rna'],
        config['atac'],
        config['meta'],
        'results/filtered_gene_peak_pairs/filtered_gene_peak_pairs_{split}.csv'
    output:
        'results/SCENT_outputs/SCENT_output_{split}.csv'
    params:
        celltype = config['celltype']
    conda:
        'envs/SCENT.yaml'
    script:
        'scripts/run_SCENT.R'

rule find_enhancer_pairs:
    input:
        expand('results/SCENT_outputs/SCENT_output_{sample}.csv', sample=SAMPLES)
    output:
        'results/SCENT_peak_gene/significant_peak_gene_associations.csv',
        expand('results/enhancer_pairs/enhancer_pairs_{sample}.csv', sample=SAMPLES),
        'results/SCENT_peak_gene/SCENT_gene_set.csv'
    conda:
        'envs/pandas.yaml'
    script:
        'scripts/find_enhancer_pairs.py'

rule run_epistasis_model_01_10:
    input:
        config['rna'],
        config['atac'],
        config['meta'],
        'results/enhancer_pairs/enhancer_pairs_{split}.csv'
    output:
        'results/epistasis_models/epistasis_models_01_10_{split}.csv'
    params:
        celltype = config['celltype']
    conda:
        'envs/seurat.yaml'
    script:
        'scripts/run_epistasis_model_01_10.R'

rule run_epistasis_model_11_00:
    input:
        config['rna'],
        config['atac'],
        config['meta'],
        'results/enhancer_pairs/enhancer_pairs_{split}.csv'
    output:
        'results/epistasis_models/epistasis_models_11_00_{split}.csv'
    params:
        celltype = config['celltype']
    conda:
        'envs/seurat.yaml'
    script:
        'scripts/run_epistasis_model_11_00.R'

rule all:
    input:
        'results/SCENT_peak_gene/significant_peak_gene_associations.csv',
        'results/SCENT_peak_gene/SCENT_gene_set.csv',
        expand('results/epistasis_models/epistasis_models_01_10_{split}.csv', split=SAMPLES),
        expand('results/epistasis_models/epistasis_models_11_00_{split}.csv', split=SAMPLES)